package nt.ddeoid.accountbook.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme —— 用 Material 3 默认紫色系作种子。
internal val LightPrimary = Color(0xFF6750A4)
internal val LightOnPrimary = Color(0xFFFFFFFF)
internal val LightPrimaryContainer = Color(0xFFEADDFF)
internal val LightOnPrimaryContainer = Color(0xFF21005D)
internal val LightSecondary = Color(0xFF625B71)
internal val LightOnSecondary = Color(0xFFFFFFFF)
internal val LightSecondaryContainer = Color(0xFFE8DEF8)
internal val LightOnSecondaryContainer = Color(0xFF1D192B)
internal val LightTertiary = Color(0xFF7D5260)
internal val LightBackground = Color(0xFFFFFBFE)
internal val LightOnBackground = Color(0xFF1C1B1F)
internal val LightSurface = Color(0xFFFFFBFE)
internal val LightOnSurface = Color(0xFF1C1B1F)
internal val LightSurfaceVariant = Color(0xFFE7E0EC)
internal val LightOnSurfaceVariant = Color(0xFF49454F)
internal val LightOutline = Color(0xFF79747E)

// Dark scheme —— 标准 M3 深色。
internal val DarkPrimary = Color(0xFFD0BCFF)
internal val DarkOnPrimary = Color(0xFF381E72)
internal val DarkPrimaryContainer = Color(0xFF4F378B)
internal val DarkOnPrimaryContainer = Color(0xFFEADDFF)
internal val DarkSecondary = Color(0xFFCCC2DC)
internal val DarkOnSecondary = Color(0xFF332D41)
internal val DarkSecondaryContainer = Color(0xFF4A4458)
internal val DarkOnSecondaryContainer = Color(0xFFE8DEF8)
internal val DarkTertiary = Color(0xFFEFB8C8)
internal val DarkBackground = Color(0xFF1C1B1F)
internal val DarkOnBackground = Color(0xFFE6E1E5)
internal val DarkSurface = Color(0xFF1C1B1F)
internal val DarkOnSurface = Color(0xFFE6E1E5)
internal val DarkSurfaceVariant = Color(0xFF49454F)
internal val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
internal val DarkOutline = Color(0xFF938F99)

// AMOLED —— 纯黑 + 高饱和紫强调色,适合 OLED 省电 + 户外强光下暗模式。
internal val AmoledPrimary = Color(0xFFD0BCFF)
internal val AmoledOnPrimary = Color(0xFF000000)
internal val AmoledPrimaryContainer = Color(0xFF4F378B)
internal val AmoledOnPrimaryContainer = Color(0xFFEADDFF)
internal val AmoledBackground = Color(0xFF000000)
internal val AmoledOnBackground = Color(0xFFEDEDED)
internal val AmoledSurface = Color(0xFF000000)
internal val AmoledOnSurface = Color(0xFFEDEDED)
internal val AmoledSurfaceVariant = Color(0xFF1B1B1B)
internal val AmoledOnSurfaceVariant = Color(0xFFB7B7B7)
internal val AmoledOutline = Color(0xFF555555)
internal val AmoledSecondary = Color(0xFFCCC2DC)
internal val AmoledOnSecondary = Color(0xFF000000)
internal val AmoledSecondaryContainer = Color(0xFF4A4458)
internal val AmoledOnSecondaryContainer = Color(0xFFE8DEF8)
internal val AmoledTertiary = Color(0xFFEFB8C8)
internal val AmoledError = Color(0xFFFFB4AB)
internal val AmoledOnError = Color(0xFF000000)

// 内置标签色 —— 与 Material 3 调色板协调的 6 色。
val TagSocial = Color(0xFFD0BCFF)
val TagShopping = Color(0xFFFFB4AB)
val TagFinance = Color(0xFF80D8FF)
val TagWork = Color(0xFFC5E1A5)
val TagTool = Color(0xFFFFE082)
val TagOther = Color(0xFFB0BEC5)